import Head from 'next/head'
import Header from "../components/Header"
import Navbar from "../components/Navbar"
import Results from "../components/Results"
import requests from "../utils/requests"


export default function Home({results}) {
  return (
    <div className="">
      <Head>
        <title>IMDb clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Navbar />

      <Results results={results} />

  
    </div>
  )
}

export async function getServerSideProps(context){
  const genre = context.query.genre || "fetchTrending"
  const baseUrl = "https://api.themoviedb.org/3"
  
  const request = await fetch(`
    ${baseUrl}${requests[genre].url}
  `).then(response => response.json());

  return {
    props: {
      results: request.results
        }
  }
}